import type { QueryRunner } from 'typeorm';

import { createEnumType, runQueries } from './migration-utils';

const EXTENDED_QUERIES: string[] = [
  createEnumType('voice_calls_direction_enum', ['INBOUND', 'OUTBOUND']),
  createEnumType('voice_phone_numbers_status_enum', ['ACTIVE', 'RELEASED', 'PENDING']),
  createEnumType('whatsapp_messages_direction_enum', ['INBOUND', 'OUTBOUND']),
  createEnumType('whatsapp_broadcasts_status_enum', ['DRAFT', 'SCHEDULED', 'SENDING', 'COMPLETED', 'FAILED']),
  createEnumType('fine_tuning_jobs_status_enum', ['PENDING', 'TRAINING', 'COMPLETED', 'FAILED', 'CANCELLED']),
  createEnumType('analytics_reports_status_enum', ['DRAFT', 'READY', 'RUNNING', 'FAILED']),
  createEnumType('tickets_status_enum', ['OPEN', 'IN_PROGRESS', 'PENDING_CUSTOMER', 'RESOLVED', 'CLOSED']),
  createEnumType('tickets_priority_enum', ['URGENT', 'HIGH', 'MEDIUM', 'LOW']),
  createEnumType('articles_status_enum', ['DRAFT', 'PUBLISHED', 'ARCHIVED']),
  createEnumType('data_jobs_type_enum', ['IMPORT', 'EXPORT', 'BACKUP']),
  createEnumType('data_jobs_status_enum', ['PENDING', 'PROCESSING', 'COMPLETED', 'FAILED']),
  createEnumType('crm_emails_direction_enum', ['INBOUND', 'OUTBOUND']),
  createEnumType('social_posts_platform_enum', ['FACEBOOK', 'TWITTER', 'LINKEDIN', 'INSTAGRAM']),
  createEnumType('social_posts_status_enum', ['DRAFT', 'SCHEDULED', 'POSTED', 'FAILED']),
  createEnumType('campaigns_type_enum', ['VOICE', 'WHATSAPP', 'EMAIL', 'SMS']),
  createEnumType('campaigns_status_enum', ['DRAFT', 'SCHEDULED', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED']),
  createEnumType('scheduled_jobs_status_enum', ['enabled', 'disabled', 'running', 'failed']),

  `CREATE TABLE IF NOT EXISTS voice_calls (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    sid varchar NOT NULL UNIQUE,
    "from" varchar NOT NULL,
    "to" varchar NOT NULL,
    direction "voice_calls_direction_enum" NOT NULL,
    status varchar NOT NULL DEFAULT 'QUEUED',
    duration_seconds integer NOT NULL DEFAULT 0,
    recording_url varchar,
    transcript text,
    ai_summary text,
    sentiment varchar(20),
    voice_profile varchar(50),
    cost_amount decimal(10,4) NOT NULL DEFAULT 0
  )`,
  `ALTER TABLE voice_calls ADD COLUMN IF NOT EXISTS ai_summary text`,
  `ALTER TABLE voice_calls ADD COLUMN IF NOT EXISTS sentiment varchar(20)`,
  `ALTER TABLE voice_calls ADD COLUMN IF NOT EXISTS voice_profile varchar(50)`,
  `CREATE INDEX IF NOT EXISTS idx_voice_calls_tenant_sid ON voice_calls(tenant_id, sid)`,

  `CREATE TABLE IF NOT EXISTS voice_phone_numbers (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    phone_number varchar(30) NOT NULL,
    country varchar(5) NOT NULL,
    status "voice_phone_numbers_status_enum" NOT NULL DEFAULT 'ACTIVE',
    twilio_sid varchar,
    capabilities jsonb NOT NULL DEFAULT '{}'
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_voice_phone_numbers_tenant ON voice_phone_numbers(tenant_id, phone_number)`,

  `CREATE TABLE IF NOT EXISTS whatsapp_messages (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    message_sid varchar NOT NULL UNIQUE,
    "from" varchar NOT NULL,
    "to" varchar NOT NULL,
    body text NOT NULL,
    direction "whatsapp_messages_direction_enum" NOT NULL,
    status varchar NOT NULL DEFAULT 'SENT',
    media_urls text[] NOT NULL DEFAULT '{}'
  )`,
  `CREATE INDEX IF NOT EXISTS idx_whatsapp_messages_tenant_sid ON whatsapp_messages(tenant_id, message_sid)`,

  `CREATE TABLE IF NOT EXISTS whatsapp_broadcasts (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    name varchar(255) NOT NULL,
    template_id uuid NOT NULL,
    template_variables jsonb NOT NULL DEFAULT '{}',
    contact_filter jsonb NOT NULL DEFAULT '{}',
    scheduled_at timestamptz,
    status "whatsapp_broadcasts_status_enum" NOT NULL DEFAULT 'DRAFT',
    total integer NOT NULL DEFAULT 0,
    sent integer NOT NULL DEFAULT 0,
    delivered integer NOT NULL DEFAULT 0,
    read integer NOT NULL DEFAULT 0,
    failed integer NOT NULL DEFAULT 0
  )`,

  `CREATE TABLE IF NOT EXISTS agents (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    name varchar(255) NOT NULL,
    description text,
    voice varchar(50) NOT NULL DEFAULT 'shimmer',
    "systemPrompt" text,
    configuration jsonb,
    "isActive" boolean NOT NULL DEFAULT true
  )`,

  `CREATE TABLE IF NOT EXISTS knowledge_bases (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    name varchar(255) NOT NULL,
    description text,
    source_type varchar NOT NULL,
    source_config jsonb NOT NULL DEFAULT '{}',
    vector_collection_name varchar,
    status varchar NOT NULL DEFAULT 'PROCESSING',
    index_meta jsonb NOT NULL DEFAULT '{}'
  )`,
  `CREATE INDEX IF NOT EXISTS idx_knowledge_bases_tenant_name ON knowledge_bases(tenant_id, name)`,

  `CREATE TABLE IF NOT EXISTS fine_tuning_jobs (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    name varchar(255) NOT NULL,
    base_model varchar(100) NOT NULL,
    fine_tuned_model varchar(100),
    status "fine_tuning_jobs_status_enum" NOT NULL DEFAULT 'PENDING',
    dataset_file_key varchar,
    openai_job_id varchar(100),
    hyperparameters jsonb NOT NULL DEFAULT '{}',
    error_message text,
    completed_at timestamptz
  )`,

  `CREATE TABLE IF NOT EXISTS analytics_dashboards (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    name varchar(255) NOT NULL,
    description text,
    widgets jsonb NOT NULL DEFAULT '[]',
    is_default boolean NOT NULL DEFAULT false
  )`,

  `CREATE TABLE IF NOT EXISTS analytics_reports (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    name varchar(255) NOT NULL,
    description text,
    report_type varchar(50) NOT NULL DEFAULT 'OVERVIEW',
    filters jsonb NOT NULL DEFAULT '{}',
    schedule jsonb,
    status "analytics_reports_status_enum" NOT NULL DEFAULT 'DRAFT',
    last_run_at timestamptz,
    last_results jsonb
  )`,

  `CREATE TABLE IF NOT EXISTS dashboard_metrics (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    metric_name varchar(100) NOT NULL,
    value decimal(20,2) NOT NULL,
    period varchar(20) NOT NULL,
    captured_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_dashboard_metrics_tenant ON dashboard_metrics(tenant_id, metric_name, period)`,

  `CREATE TABLE IF NOT EXISTS tickets (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    ticket_number varchar(20) NOT NULL UNIQUE,
    subject varchar(500) NOT NULL,
    description text NOT NULL,
    contact_id uuid,
    assignee_id uuid,
    status "tickets_status_enum" NOT NULL DEFAULT 'OPEN',
    priority "tickets_priority_enum" NOT NULL DEFAULT 'MEDIUM',
    last_replied_at timestamptz,
    resolved_at timestamptz,
    metadata jsonb
  )`,
  `CREATE INDEX IF NOT EXISTS idx_tickets_tenant_status ON tickets(tenant_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_tickets_tenant_priority ON tickets(tenant_id, priority)`,

  `CREATE TABLE IF NOT EXISTS articles (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    title varchar(500) NOT NULL,
    slug varchar(600) NOT NULL UNIQUE,
    content text NOT NULL,
    category varchar(200),
    status "articles_status_enum" NOT NULL DEFAULT 'DRAFT',
    author_id uuid,
    views integer NOT NULL DEFAULT 0,
    metadata jsonb
  )`,
  `CREATE INDEX IF NOT EXISTS idx_articles_tenant_status ON articles(tenant_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_articles_tenant_category ON articles(tenant_id, category)`,

  `CREATE TABLE IF NOT EXISTS storage_files (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    filename varchar(255) NOT NULL,
    object_key varchar(500) NOT NULL,
    mime_type varchar(100) NOT NULL,
    size bigint NOT NULL DEFAULT 0,
    bucket varchar(100) NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_storage_files_tenant_key ON storage_files(tenant_id, object_key)`,

  `CREATE TABLE IF NOT EXISTS data_jobs (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    type "data_jobs_type_enum" NOT NULL,
    status "data_jobs_status_enum" NOT NULL DEFAULT 'PENDING',
    entity_type varchar(50),
    file_key varchar,
    download_url text,
    metadata jsonb NOT NULL DEFAULT '{}',
    error_message text,
    completed_at timestamptz
  )`,
  `CREATE INDEX IF NOT EXISTS idx_data_jobs_tenant_type_status ON data_jobs(tenant_id, type, status)`,

  `CREATE TABLE IF NOT EXISTS oauth_apps (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    name varchar(255) NOT NULL,
    client_id varchar(64) NOT NULL UNIQUE,
    client_secret_hash varchar NOT NULL,
    client_secret_prefix varchar(16) NOT NULL,
    redirect_uris text[] NOT NULL DEFAULT '{}',
    scopes text[] NOT NULL DEFAULT '{}',
    is_active boolean NOT NULL DEFAULT true
  )`,

  `CREATE TABLE IF NOT EXISTS usage_records (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    metric varchar(100) NOT NULL,
    quantity bigint NOT NULL DEFAULT 0,
    period_start timestamptz NOT NULL,
    period_end timestamptz NOT NULL,
    unit_cost decimal(15,6) NOT NULL DEFAULT 0,
    total_cost decimal(15,2) NOT NULL DEFAULT 0,
    meta jsonb NOT NULL DEFAULT '{}'
  )`,
  `CREATE INDEX IF NOT EXISTS idx_usage_records_tenant_metric ON usage_records(tenant_id, metric, period_start, period_end)`,

  `CREATE TABLE IF NOT EXISTS deal_products (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    deal_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    unit_price decimal(15,2) NOT NULL DEFAULT 0,
    discount decimal(15,2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_deal_products_deal FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
    CONSTRAINT fk_deal_products_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_deal_products_unique ON deal_products(tenant_id, deal_id, product_id)`,

  `CREATE TABLE IF NOT EXISTS crm_emails (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    subject varchar(255) NOT NULL,
    body text NOT NULL,
    "from" varchar(255) NOT NULL,
    "to" varchar(255) NOT NULL,
    direction "crm_emails_direction_enum" NOT NULL DEFAULT 'OUTBOUND',
    "isRead" boolean NOT NULL DEFAULT false,
    "leadId" uuid,
    "contactId" uuid,
    metadata jsonb
  )`,

  `CREATE TABLE IF NOT EXISTS social_posts (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    platform "social_posts_platform_enum" NOT NULL,
    content text NOT NULL,
    "mediaUrls" text,
    "scheduledAt" timestamptz NOT NULL,
    status "social_posts_status_enum" NOT NULL DEFAULT 'DRAFT',
    "likesCount" integer NOT NULL DEFAULT 0,
    "sharesCount" integer NOT NULL DEFAULT 0,
    "clicksCount" integer NOT NULL DEFAULT 0,
    "failReason" text,
    "tenantId" uuid NOT NULL,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_social_posts_tenant ON social_posts("tenantId")`,

  `CREATE TABLE IF NOT EXISTS campaigns (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    name varchar(255) NOT NULL,
    type "campaigns_type_enum" NOT NULL DEFAULT 'VOICE',
    status "campaigns_status_enum" NOT NULL DEFAULT 'DRAFT',
    "agentId" varchar(255),
    "totalLeads" integer NOT NULL DEFAULT 0,
    "completedLeads" integer NOT NULL DEFAULT 0,
    "qualifiedLeads" integer NOT NULL DEFAULT 0,
    budget decimal(10,2) NOT NULL DEFAULT 0,
    spent decimal(10,2) NOT NULL DEFAULT 0,
    "scheduledAt" timestamptz,
    metadata jsonb
  )`,

  `CREATE TABLE IF NOT EXISTS announcements (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    title varchar(500) NOT NULL,
    content text NOT NULL,
    severity varchar(255) NOT NULL DEFAULT 'INFO',
    "expiresAt" timestamptz,
    "isActive" boolean NOT NULL DEFAULT true,
    target jsonb NOT NULL DEFAULT '{}'
  )`,

  `CREATE TABLE IF NOT EXISTS team_groups (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    name varchar(255) NOT NULL,
    description text,
    leader_id uuid,
    metadata jsonb
  )`,
  `CREATE INDEX IF NOT EXISTS idx_team_groups_tenant_name ON team_groups(tenant_id, name)`,

  `CREATE TABLE IF NOT EXISTS team_group_members (
    group_id uuid NOT NULL,
    user_id uuid NOT NULL,
    PRIMARY KEY (group_id, user_id),
    CONSTRAINT fk_team_group_members_group FOREIGN KEY (group_id) REFERENCES team_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_team_group_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  )`,

  `CREATE TABLE IF NOT EXISTS scheduled_jobs (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    name varchar NOT NULL,
    description text,
    cron varchar NOT NULL,
    target varchar NOT NULL,
    payload jsonb,
    status "scheduled_jobs_status_enum" NOT NULL DEFAULT 'enabled',
    last_run_at timestamptz,
    next_run_at timestamptz,
    error_message text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_scheduled_jobs_tenant ON scheduled_jobs(tenant_id)`,

  `CREATE TABLE IF NOT EXISTS error_logs (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id varchar,
    user_id varchar,
    message varchar NOT NULL,
    stack text,
    path varchar,
    method varchar,
    context jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_error_logs_tenant ON error_logs(tenant_id)`,
  `CREATE INDEX IF NOT EXISTS idx_error_logs_created ON error_logs(created_at)`,

  `CREATE TABLE IF NOT EXISTS api_logs (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid,
    user_id uuid,
    method varchar(10) NOT NULL,
    url text NOT NULL,
    status_code integer NOT NULL,
    duration_ms integer NOT NULL,
    ip_address varchar(45),
    request_headers jsonb,
    request_body jsonb,
    response_body jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_api_logs_tenant ON api_logs(tenant_id, method, url)`,

  `CREATE TABLE IF NOT EXISTS deal_histories (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    updated_by uuid,
    deal_id uuid NOT NULL,
    old_stage_id uuid,
    new_stage_id uuid NOT NULL,
    changed_by_id uuid,
    change_reason text,
    value_at_change decimal(15,2),
    probability_at_change integer,
    CONSTRAINT fk_deal_histories_deal FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
    CONSTRAINT fk_deal_histories_old_stage FOREIGN KEY (old_stage_id) REFERENCES pipeline_stages(id) ON DELETE SET NULL,
    CONSTRAINT fk_deal_histories_new_stage FOREIGN KEY (new_stage_id) REFERENCES pipeline_stages(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_deal_histories_tenant_deal ON deal_histories(tenant_id, deal_id)`,
];

const EXTENDED_DOWN_QUERIES: string[] = [
  'DROP TABLE IF EXISTS deal_histories',
  'DROP TABLE IF EXISTS api_logs',
  'DROP TABLE IF EXISTS error_logs',
  'DROP TABLE IF EXISTS scheduled_jobs',
  'DROP TABLE IF EXISTS team_group_members',
  'DROP TABLE IF EXISTS team_groups',
  'DROP TABLE IF EXISTS announcements',
  'DROP TABLE IF EXISTS campaigns',
  'DROP TABLE IF EXISTS social_posts',
  'DROP TABLE IF EXISTS crm_emails',
  'DROP TABLE IF EXISTS deal_products',
  'DROP TABLE IF EXISTS usage_records',
  'DROP TABLE IF EXISTS oauth_apps',
  'DROP TABLE IF EXISTS data_jobs',
  'DROP TABLE IF EXISTS storage_files',
  'DROP TABLE IF EXISTS articles',
  'DROP TABLE IF EXISTS tickets',
  'DROP TABLE IF EXISTS dashboard_metrics',
  'DROP TABLE IF EXISTS analytics_reports',
  'DROP TABLE IF EXISTS analytics_dashboards',
  'DROP TABLE IF EXISTS fine_tuning_jobs',
  'DROP TABLE IF EXISTS knowledge_bases',
  'DROP TABLE IF EXISTS agents',
  'DROP TABLE IF EXISTS whatsapp_broadcasts',
  'DROP TABLE IF EXISTS whatsapp_messages',
  'DROP TABLE IF EXISTS voice_phone_numbers',
  'DROP TABLE IF EXISTS voice_calls',
  'DROP TYPE IF EXISTS scheduled_jobs_status_enum',
  'DROP TYPE IF EXISTS campaigns_status_enum',
  'DROP TYPE IF EXISTS campaigns_type_enum',
  'DROP TYPE IF EXISTS social_posts_status_enum',
  'DROP TYPE IF EXISTS social_posts_platform_enum',
  'DROP TYPE IF EXISTS crm_emails_direction_enum',
  'DROP TYPE IF EXISTS data_jobs_status_enum',
  'DROP TYPE IF EXISTS data_jobs_type_enum',
  'DROP TYPE IF EXISTS articles_status_enum',
  'DROP TYPE IF EXISTS tickets_priority_enum',
  'DROP TYPE IF EXISTS tickets_status_enum',
  'DROP TYPE IF EXISTS analytics_reports_status_enum',
  'DROP TYPE IF EXISTS fine_tuning_jobs_status_enum',
  'DROP TYPE IF EXISTS whatsapp_broadcasts_status_enum',
  'DROP TYPE IF EXISTS whatsapp_messages_direction_enum',
  'DROP TYPE IF EXISTS voice_phone_numbers_status_enum',
  'DROP TYPE IF EXISTS voice_calls_direction_enum',
];

export async function upExtendedModules(queryRunner: QueryRunner): Promise<void> {
  await runQueries(queryRunner, EXTENDED_QUERIES);
}

export async function downExtendedModules(queryRunner: QueryRunner): Promise<void> {
  await runQueries(queryRunner, EXTENDED_DOWN_QUERIES);
}
